apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: cert-request
    namespace: istio-system
spec:
    secretName: tls-secret
    duration: 2160h
    renewBefore: 360h
    isCA: false
    privateKey:
        algorithm: RSA
        encoding: PKCS1
        size: 2048
    usages:
        - server auth
        - client auth
    issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer
        group: cert-manager.io
    dnsNames:
    - "rajmehta.live"
    # acme:
    #     config:
    #     - http01:
    #         ingressClass: istio