apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: cert
    namespace: istio-system
spec:
    secretName: letsencrypt-production
    duration: 2160h
    renewBefore: 360h
    isCA: false
    privateKey:
        algorithm: RSA
        encoding: PKCS1
        size: 2048
    usages:
        - server auth
        - client auth
    issuerRef:
        name: issuer
        kind: ClusterIssuer
        group: cert-manager.io
    dnsNames:
    - {{ .Values.dnsName }}
    # acme:
    #     config:
    #     - http01:
    #         ingressClass: istio
    