apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  #name: letsencrypt-production
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/director
    email: {{ .Values.issuerEmail }}
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: istio